# Generated by Django 5.1.3 on 2024-11-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WbOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_honest_sign', models.BooleanField(default=False)),
                ('wb_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'wb_orders',
            },
        ),
        migrations.CreateModel(
            name='WbOrderProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('wb_sgtin', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='app.wbordermodel')),
            ],
            options={
                'db_table': 'wb_order_products',
            },
        ),
    ]
