# Generated by Django 5.1.3 on 2024-11-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WbSupplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_supply_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'wb_supplies',
            },
        ),
        migrations.CreateModel(
            name='WbTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=256)),
                ('account', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'wb_tasks',
            },
        ),
        migrations.AddField(
            model_name='wbordermodel',
            name='qr_code',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='wborderproductmodel',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='wborderproductmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='app.wbordermodel'),
        ),
        migrations.AlterField(
            model_name='wborderproductmodel',
            name='wb_sgtin',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbordermodel',
            name='supply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.wbsupplymodel'),
        ),
        migrations.AddField(
            model_name='wbsupplymodel',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='app.wbtaskmodel'),
        ),
    ]
