# Generated by Django 5.1.3 on 2024-11-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wbsupplymodel_wbtaskmodel_wbordermodel_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wborderproductmodel',
            name='code',
            field=models.CharField(default=None, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='wbordermodel',
            name='qr_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='wborderproductmodel',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
