# Generated by Django 5.1.3 on 2024-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wborderproductmodel_code_alter_wbordermodel_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbordermodel',
            name='has_honest_sign',
        ),
        migrations.AddField(
            model_name='wborderproductmodel',
            name='has_honest_sign',
            field=models.BooleanField(default=False),
        ),
    ]
