# Generated by Django 5.1.3 on 2024-11-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_wbordermodel_has_honest_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wborderproductmodel',
            name='wb_sgtin',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
