# Generated by Django 5.1.3 on 2024-11-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_wborderproductmodel_wb_sgtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbordermodel',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.wbsupplymodel'),
        ),
    ]
